from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_DIRECTORY = PROJECT_ROOT / "data"
CONFIG_DIRECTORY = PROJECT_ROOT / "config"

BRONZE_DIRECTORY = DATA_DIRECTORY / "bronze"
SILVER_DIRECTORY = DATA_DIRECTORY / "silver"
GOLD_DIRECTORY = DATA_DIRECTORY / "gold"

BRONZE_FILE = BRONZE_DIRECTORY / "telemetry.jsonl"
SILVER_FILE = SILVER_DIRECTORY / "telemetry_clean.parquet"
REJECTED_FILE = SILVER_DIRECTORY / "rejected_events.jsonl"

LOCATION_METRICS_FILE = GOLD_DIRECTORY / "location_metrics.parquet"
HOURLY_METRICS_FILE = GOLD_DIRECTORY / "hourly_metrics.parquet"
DEVICE_HEALTH_FILE = GOLD_DIRECTORY / "device_health.parquet"

BUILDINGS_FILE = CONFIG_DIRECTORY / "buildings.json"
DEVICE_TEMPLATES_FILE = CONFIG_DIRECTORY / "device_templates.json"
SIMULATION_FILE = CONFIG_DIRECTORY / "simulation.json"

MIN_TEMPERATURE = 50
MAX_TEMPERATURE = 120

MIN_HUMIDITY = 0
MAX_HUMIDITY = 100

MIN_ENERGY_USAGE = 0
MIN_AIR_QUALITY = 0
MAX_AIR_QUALITY = 500

MIN_OCCUPANCY = 0

DEVICE_OFFLINE_MINUTES = 5
TEMPERATURE_ALERT_THRESHOLD = 78